fullnameOverride: authentik-postgres
ignoreHelmHooks: true
postgres:
  - name: authentik-postgres
    enabled: true
    instances: 1
    imageName: ghcr.io/cloudnative-pg/postgresql:15.1  # https://github.com/cloudnative-pg/postgres-containers/pkgs/container/postgresql
    resources:
      requests:
        cpu: "20m"
        memory: "64Mi"
    storage:
      size: 2Gi
      storageClass: standard
      resizeInUseVolumes: true
    walStorage:
      size: 1Gi
      storageClass: standard
      resizeInUseVolumes: true