source: https://github.com/pawe/gxfs-workshop.git
sourceRef: main
namespace: argocd

applications:
  - name: app-of-apps
    project: gitops
    enabled: true
    sourcePath: argocd
    helmValues:
      - ../clusters/testing/configuration.yaml

  - name: gitops
    project: gitops
    enabled: true
    sourcePath: argocd
    helmValues:
      - ../clusters/testing/values/gitops.yaml

  - name: base-apps
    project: base
    enabled: true
    sourcePath: argocd
    helmValues:
      - ../clusters/testing/values/base.yaml

  - name: idm
    project: idm
    enabled: true
    sourcePath: argocd
    helmValues:
      - ../clusters/testing/values/idm.yaml

  - name: gxfs-portal
    project: gxfs-portal
    enabled: true
    sourcePath: argocd
    helmValues:
      - ../clusters/testing/values/gxfs-portal.yaml

projects:
  - name: gitops
    enabled: true
    destinations:
    - namespace: '*'
      server: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  - name: base
    enabled: true
    destinations:
    - namespace: '*'
      server: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  - name: idm
    enabled: true
    destinations:
    - namespace: '*'
      server: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  - name: gxfs-portal
    enabled: true
    destinations:
    - namespace: '*'
      server: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
